# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_TelaLogin(object):
    def setupUi(self, TelaLogin):
        TelaLogin.setObjectName("TelaLogin")
        TelaLogin.resize(320, 240)
        self.btEntrar = QtWidgets.QPushButton(TelaLogin)
        self.btEntrar.setGeometry(QtCore.QRect(110, 188, 99, 30))
        self.btEntrar.setObjectName("btEntrar")
        self.txLogin = QtWidgets.QLineEdit(TelaLogin)
        self.txLogin.setGeometry(QtCore.QRect(60, 40, 200, 32))
        self.txLogin.setObjectName("txLogin")
        self.txSenha = QtWidgets.QLineEdit(TelaLogin)
        self.txSenha.setGeometry(QtCore.QRect(60, 130, 200, 32))
        self.txSenha.setInputMask("")
        self.txSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txSenha.setObjectName("txSenha")
        self.label = QtWidgets.QLabel(TelaLogin)
        self.label.setGeometry(QtCore.QRect(60, 10, 68, 22))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(TelaLogin)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 68, 22))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(TelaLogin)
        QtCore.QMetaObject.connectSlotsByName(TelaLogin)

    def retranslateUi(self, TelaLogin):
        _translate = QtCore.QCoreApplication.translate
        TelaLogin.setWindowTitle(_translate("TelaLogin", "TelaLogin"))
        self.btEntrar.setText(_translate("TelaLogin", "ENTRAR"))
        self.label.setText(_translate("TelaLogin", "Login"))
        self.label_2.setText(_translate("TelaLogin", "Senha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaLogin = QtWidgets.QWidget()
    ui = Ui_TelaLogin()
    ui.setupUi(TelaLogin)
    TelaLogin.show()
    sys.exit(app.exec_())
