# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/tela_view_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaViewLogin(object):
    def setupUi(self, TelaViewLogin):
        TelaViewLogin.setObjectName("TelaViewLogin")
        TelaViewLogin.resize(1024, 768)
        self.tblViewLogin = QtWidgets.QTableView(TelaViewLogin)
        self.tblViewLogin.setGeometry(QtCore.QRect(30, 40, 961, 571))
        self.tblViewLogin.setObjectName("tblViewLogin")
        self.btVoltar = QtWidgets.QPushButton(TelaViewLogin)
        self.btVoltar.setGeometry(QtCore.QRect(400, 630, 212, 102))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btVoltar.setFont(font)
        self.btVoltar.setObjectName("btVoltar")

        self.retranslateUi(TelaViewLogin)
        QtCore.QMetaObject.connectSlotsByName(TelaViewLogin)

    def retranslateUi(self, TelaViewLogin):
        _translate = QtCore.QCoreApplication.translate
        TelaViewLogin.setWindowTitle(_translate("TelaViewLogin", "Form"))
        self.btVoltar.setText(_translate("TelaViewLogin", "VOLTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaViewLogin = QtWidgets.QWidget()
    ui = Ui_TelaViewLogin()
    ui.setupUi(TelaViewLogin)
    TelaViewLogin.show()
    sys.exit(app.exec_())
