# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaCadastroUser(object):
    def setupUi(self, TelaCadastroUser):
        TelaCadastroUser.setObjectName("TelaCadastroUser")
        TelaCadastroUser.resize(1024, 768)
        self.txLogin = QtWidgets.QLineEdit(TelaCadastroUser)
        self.txLogin.setGeometry(QtCore.QRect(140, 90, 710, 64))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txLogin.setFont(font)
        self.txLogin.setObjectName("txLogin")
        self.txSenha = QtWidgets.QLineEdit(TelaCadastroUser)
        self.txSenha.setGeometry(QtCore.QRect(140, 250, 710, 64))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txSenha.setFont(font)
        self.txSenha.setObjectName("txSenha")
        self.btCadastrar = QtWidgets.QPushButton(TelaCadastroUser)
        self.btCadastrar.setGeometry(QtCore.QRect(210, 600, 190, 102))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btCadastrar.setFont(font)
        self.btCadastrar.setObjectName("btCadastrar")
        self.btLocalizar = QtWidgets.QPushButton(TelaCadastroUser)
        self.btLocalizar.setGeometry(QtCore.QRect(10, 600, 190, 102))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btLocalizar.setFont(font)
        self.btLocalizar.setObjectName("btLocalizar")
        self.btDeletar = QtWidgets.QPushButton(TelaCadastroUser)
        self.btDeletar.setGeometry(QtCore.QRect(410, 600, 190, 102))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btDeletar.setFont(font)
        self.btDeletar.setObjectName("btDeletar")
        self.btAtualizar = QtWidgets.QPushButton(TelaCadastroUser)
        self.btAtualizar.setGeometry(QtCore.QRect(610, 600, 190, 102))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btAtualizar.setFont(font)
        self.btAtualizar.setObjectName("btAtualizar")
        self.btSair = QtWidgets.QPushButton(TelaCadastroUser)
        self.btSair.setGeometry(QtCore.QRect(810, 600, 190, 102))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btSair.setFont(font)
        self.btSair.setObjectName("btSair")
        self.label = QtWidgets.QLabel(TelaCadastroUser)
        self.label.setGeometry(QtCore.QRect(140, 60, 68, 22))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(TelaCadastroUser)
        self.label_2.setGeometry(QtCore.QRect(140, 220, 68, 22))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(TelaCadastroUser)
        self.groupBox.setGeometry(QtCore.QRect(140, 360, 291, 131))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.rbtOperador = QtWidgets.QRadioButton(self.groupBox)
        self.rbtOperador.setGeometry(QtCore.QRect(20, 40, 201, 31))
        self.rbtOperador.setObjectName("rbtOperador")
        self.rbtAdm = QtWidgets.QRadioButton(self.groupBox)
        self.rbtAdm.setGeometry(QtCore.QRect(20, 100, 191, 31))
        self.rbtAdm.setObjectName("rbtAdm")
        self.rbtInvisible = QtWidgets.QRadioButton(self.groupBox)
        self.rbtInvisible.setGeometry(QtCore.QRect(20, 150, 191, 27))
        self.rbtInvisible.setObjectName("rbtInvisible")

        self.retranslateUi(TelaCadastroUser)
        QtCore.QMetaObject.connectSlotsByName(TelaCadastroUser)

    def retranslateUi(self, TelaCadastroUser):
        _translate = QtCore.QCoreApplication.translate
        TelaCadastroUser.setWindowTitle(_translate("TelaCadastroUser", "Form"))
        self.btCadastrar.setText(_translate("TelaCadastroUser", "CADASTRAR"))
        self.btLocalizar.setText(_translate("TelaCadastroUser", "LOCALIZAR"))
        self.btDeletar.setText(_translate("TelaCadastroUser", "DELETAR"))
        self.btAtualizar.setText(_translate("TelaCadastroUser", "ATUALIZAR"))
        self.btSair.setText(_translate("TelaCadastroUser", "SAIR"))
        self.label.setText(_translate("TelaCadastroUser", "Login"))
        self.label_2.setText(_translate("TelaCadastroUser", "Senha"))
        self.groupBox.setTitle(_translate("TelaCadastroUser", "Permissões"))
        self.rbtOperador.setText(_translate("TelaCadastroUser", "Operador"))
        self.rbtAdm.setText(_translate("TelaCadastroUser", "Administrador"))
        self.rbtInvisible.setText(_translate("TelaCadastroUser", "RadioButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaCadastroUser = QtWidgets.QWidget()
    ui = Ui_TelaCadastroUser()
    ui.setupUi(TelaCadastroUser)
    TelaCadastroUser.show()
    sys.exit(app.exec_())
