# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/tela_view_rotina.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaViewRotina(object):
    def setupUi(self, TelaViewRotina):
        TelaViewRotina.setObjectName("TelaViewRotina")
        TelaViewRotina.resize(1024, 768)
        self.tblViewRotina = QtWidgets.QTableView(TelaViewRotina)
        self.tblViewRotina.setGeometry(QtCore.QRect(30, 40, 961, 571))
        self.tblViewRotina.setObjectName("tblViewRotina")
        self.btVoltar = QtWidgets.QPushButton(TelaViewRotina)
        self.btVoltar.setGeometry(QtCore.QRect(400, 701, 212, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btVoltar.setFont(font)
        self.btVoltar.setObjectName("btVoltar")

        self.retranslateUi(TelaViewRotina)
        QtCore.QMetaObject.connectSlotsByName(TelaViewRotina)

    def retranslateUi(self, TelaViewRotina):
        _translate = QtCore.QCoreApplication.translate
        TelaViewRotina.setWindowTitle(_translate("TelaViewRotina", "Form"))
        self.btVoltar.setText(_translate("TelaViewRotina", "VOLTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaViewRotina = QtWidgets.QWidget()
    ui = Ui_TelaViewRotina()
    ui.setupUi(TelaViewRotina)
    TelaViewRotina.show()
    sys.exit(app.exec_())
