# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/tela_configuracao.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaConfiguracao(object):
    def setupUi(self, TelaConfiguracao):
        TelaConfiguracao.setObjectName("TelaConfiguracao")
        TelaConfiguracao.resize(1024, 768)
        self.btCadastro = QtWidgets.QPushButton(TelaConfiguracao)
        self.btCadastro.setGeometry(QtCore.QRect(680, 90, 290, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btCadastro.setFont(font)
        self.btCadastro.setObjectName("btCadastro")
        self.btCarregarDados = QtWidgets.QPushButton(TelaConfiguracao)
        self.btCarregarDados.setGeometry(QtCore.QRect(60, 90, 290, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btCarregarDados.setFont(font)
        self.btCarregarDados.setObjectName("btCarregarDados")
        self.btVoltar = QtWidgets.QPushButton(TelaConfiguracao)
        self.btVoltar.setGeometry(QtCore.QRect(400, 540, 212, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btVoltar.setFont(font)
        self.btVoltar.setObjectName("btVoltar")
        self.btCriarReceita = QtWidgets.QPushButton(TelaConfiguracao)
        self.btCriarReceita.setGeometry(QtCore.QRect(370, 90, 290, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btCriarReceita.setFont(font)
        self.btCriarReceita.setObjectName("btCriarReceita")

        self.retranslateUi(TelaConfiguracao)
        QtCore.QMetaObject.connectSlotsByName(TelaConfiguracao)

    def retranslateUi(self, TelaConfiguracao):
        _translate = QtCore.QCoreApplication.translate
        TelaConfiguracao.setWindowTitle(_translate("TelaConfiguracao", "Form"))
        self.btCadastro.setText(_translate("TelaConfiguracao", "CADASTROS USUÁRIO"))
        self.btCarregarDados.setText(_translate("TelaConfiguracao", "CARREGAR DADOS"))
        self.btVoltar.setText(_translate("TelaConfiguracao", "VOLTAR"))
        self.btCriarReceita.setText(_translate("TelaConfiguracao", "CRIAR PROGRAMA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaConfiguracao = QtWidgets.QWidget()
    ui = Ui_TelaConfiguracao()
    ui.setupUi(TelaConfiguracao)
    TelaConfiguracao.show()
    sys.exit(app.exec_())
