# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/tela_view_receita.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaViewReceita(object):
    def setupUi(self, TelaViewReceita):
        TelaViewReceita.setObjectName("TelaViewReceita")
        TelaViewReceita.resize(1024, 768)
        self.tblViewReceita = QtWidgets.QTableView(TelaViewReceita)
        self.tblViewReceita.setGeometry(QtCore.QRect(30, 40, 961, 571))
        self.tblViewReceita.setObjectName("tblViewReceita")
        self.btVoltar = QtWidgets.QPushButton(TelaViewReceita)
        self.btVoltar.setGeometry(QtCore.QRect(400, 630, 212, 102))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btVoltar.setFont(font)
        self.btVoltar.setObjectName("btVoltar")

        self.retranslateUi(TelaViewReceita)
        QtCore.QMetaObject.connectSlotsByName(TelaViewReceita)

    def retranslateUi(self, TelaViewReceita):
        _translate = QtCore.QCoreApplication.translate
        TelaViewReceita.setWindowTitle(_translate("TelaViewReceita", "Form"))
        self.btVoltar.setText(_translate("TelaViewReceita", "VOLTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaViewReceita = QtWidgets.QWidget()
    ui = Ui_TelaViewReceita()
    ui.setupUi(TelaViewReceita)
    TelaViewReceita.show()
    sys.exit(app.exec_())
